spring:
  profiles: dev

  thymeleaf:
    cache: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  basic:
    enabled: true
    authorize-mode: NONE
#server:
#  port: 8080
#  ssl:
#    key-store: file:////Users/innocentjr/Downloads/demo/mykeys.jks
#    key-store-password: letmein
#    key-password: letmein

logging:
  path: /vars/logs/
  file: Tacos.log
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
com:
  example:
    demo:
      orders: 10